#
# Generated file. Do not edit.
# This file is machine generated by flutter for the Windows build.
#

cmake_minimum_required(VERSION 3.14)

set(FLUTTER_MANAGED_CMAKE "generated_plugins")

list(APPEND FLUTTER_PLUGIN_LIST
  # Plugin list here
)

set(FLUTTER_PLUGIN_PATH "${CMAKE_CURRENT_SOURCE_DIR}/..")
set(FLUTTER_ROOT "${FLUTTER_EPHEMERAL_DIR}")

add_library(flutter_windows SHARED IMPORTED GLOBAL)
set_target_properties(flutter_windows PROPERTIES
  IMPORTED_LOCATION "${FLUTTER_EPHEMERAL_DIR}/flutter_windows/flutter_windows.dll"
  IMPORTED_IMPLIB "${FLUTTER_EPHEMERAL_DIR}/flutter_windows/flutter_windows.lib"
  INTERFACE_INCLUDE_DIRECTORIES "${FLUTTER_EPHEMERAL_DIR}/flutter_windows"
)

if(FLUTTER_PLUGIN_LIST)
  foreach(plugin_name ${FLUTTER_PLUGIN_LIST})
    add_subdirectory("${FLUTTER_PLUGIN_PATH}/${plugin_name}/windows" plugins/${plugin_name})
    target_link_libraries(${PROJECT_NAME} PUBLIC ${plugin_name}_plugin)
    list(APPEND FLUTTER_LIBS ${plugin_name}_plugin)
  endforeach()
endif()
